[build]
  publish = "dist"
  command = "npm run build"

[[redirects]]
  from = "/causes/*"
  to = "/causes.html"
  status = 200

[[redirects]]
  from = "/causes"
  to = "/causes.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200